owner: andreesg # Your GitHub username
repo: intk-upptime # Your Github repository name
sites:
  - name: Museum Hilversum
    url: https://new.museumhilversum.nl
  - name: SCHUNCK
    url: https://www.schunck.nl
  - name: Uitgeverij Komma
    url: https://www.uitgeverijkomma.nl
  - name: Haags Historisch Museum
    url: https://www.haagshistorischmuseum.nl
  - name: Centraal Museum
    url: https://www.centraalmuseum.nl
  - name: Bonnefanten
    url: https://www.bonnefanten.nl
  - name: Het Park
    url: https://www.hetpark.nl
  - name: De Gevangenpoort
    url: https://www.gevangenpoort.nl
  - name: Historisch Museum Den Briel
    url: https://www.historischmuseumdenbriel.nl
  - name: Rietveld Schröderhuis
    url: https://www.rietveldschroderhuis.nl
  - name: Cuypershuis
    url: https://www.cuypershuis.nl
  - name: Historiehuis
    url: https://www.historiehuis.nl
  - name: Archief Roermond
    url: https://www.archiefroermond.nl
  - name: Veenkoloniaal Museum
    url: https://www.veenkoloniaalmuseum.nl
  - name: Kunsthal KAdE
    url: https://www.kunsthalkade.nl
  - name: Mondriaanhuis
    url: https://www.mondriaanhuis.nl
  - name: Zeeuws Museum
    url: https://www.zeeuwsmuseum.nl
  - name: Zeeuws Museum Jaarverslag
    url: http://jaarverslag.zeeuwsmuseum.nl
  - name: Het Markiezenhof
    url: https://www.markiezenhof.nl
  - name: Teylers Museum
    url: https://www.teylersmuseum.nl
  - name: INTK
    url: https://www.intk.com/en
  - name: INTK development server
    url: https://dev.intk.com

user-agent: andreesg

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.intk.com
  logoUrl: https://old.intk.com/logo.png
  name: INTK
  introTitle: "Monitor the uptime of INTK projects"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
