owner: intk # Your GitHub username
repo: intk-upptime # Your Github repository name
sites:
  - name: Haags Historisch Museum
    url: https://www.haagshistorischmuseum.nl
  - name: Bonnefanten
    url: https://www.bonnefanten.nl
  - name: De Gevangenpoort
    url: https://www.gevangenpoort.nl
  - name: Cuypershuis
    url: https://www.cuypershuis.nl
  - name: Historiehuis
    url: https://www.historiehuis.nl
  - name: Archief Roermond
    url: https://www.archiefroermond.nl
  - name: Veenkoloniaal Museum
    url: https://www.veenkoloniaalmuseum.nl
  - name: Zeeuws Museum
    url: https://www.zeeuwsmuseum.nl
  - name: Zeeuws Museum Jaarverslag
    url: http://jaarverslag.zeeuwsmuseum.nl
  - name: Het Markiezenhof
    url: https://www.markiezenhof.nl
  - name: INTK
    url: https://www.intk.com/en
  - name: New Zeeuws Museum
    url: https://new.zeeuwsmuseum.nl/nl/over-het-museum/publicaties/

user-agent: andreesg

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 0,6-23 * * *"

status-website:
  baseUrl: /intk-upptime
  logoUrl: https://old.intk.com/logo.png
  name: INTK
  introTitle: "Monitor the uptime of INTK projects"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
